# Form implementation generated from reading ui file 'gui.ui'
#
# Created by: PyQt6 UI code generator 6.5.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_ExifGUI(object):
    def setupUi(self, ExifGUI):
        ExifGUI.setObjectName("ExifGUI")
        ExifGUI.resize(705, 563)
        self.centralwidget = QtWidgets.QWidget(parent=ExifGUI)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.butt_metadata = QtWidgets.QPushButton(parent=self.centralwidget)
        self.butt_metadata.setMinimumSize(QtCore.QSize(110, 40))
        self.butt_metadata.setMaximumSize(QtCore.QSize(120, 60))
        self.butt_metadata.setObjectName("butt_metadata")
        self.verticalLayout.addWidget(self.butt_metadata)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.table = QtWidgets.QTableWidget(parent=self.centralwidget)
        self.table.setMinimumSize(QtCore.QSize(300, 500))
        self.table.setMaximumSize(QtCore.QSize(1000, 700))
        self.table.setObjectName("table")
        self.table.setColumnCount(0)
        self.table.setRowCount(0)
        self.horizontalLayout.addWidget(self.table)
        self.gridLayout.addLayout(self.horizontalLayout, 0, 0, 1, 1)
        ExifGUI.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=ExifGUI)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 705, 22))
        self.menubar.setObjectName("menubar")
        ExifGUI.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=ExifGUI)
        self.statusbar.setObjectName("statusbar")
        ExifGUI.setStatusBar(self.statusbar)

        self.retranslateUi(ExifGUI)
        QtCore.QMetaObject.connectSlotsByName(ExifGUI)

    def retranslateUi(self, ExifGUI):
        _translate = QtCore.QCoreApplication.translate
        ExifGUI.setWindowTitle(_translate("ExifGUI", "Exif GUI"))
        self.butt_metadata.setText(_translate("ExifGUI", "Wybierz plik"))
